//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCShoppingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVCVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVCVendor()
        {
            this.MVCProducts = new HashSet<MVCProduct>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string Image { get; set; }
        public string WebsiteURL { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVCProduct> MVCProducts { get; set; }
    }
}
